export interface PaisDdi {
  nome: string;
  ddi: string;
}

// Lista dos países mais relevantes para o público de uma agência de viagens
// brasileira (não é a lista completa ISO 3166 — cobre os destinos e origens
// de clientes mais comuns).
export const PAISES_DDI: PaisDdi[] = [
  { nome: "Brasil", ddi: "+55" },
  { nome: "Estados Unidos / Canadá", ddi: "+1" },
  { nome: "Portugal", ddi: "+351" },
  { nome: "Argentina", ddi: "+54" },
  { nome: "Chile", ddi: "+56" },
  { nome: "Uruguai", ddi: "+598" },
  { nome: "Paraguai", ddi: "+595" },
  { nome: "Bolívia", ddi: "+591" },
  { nome: "Peru", ddi: "+51" },
  { nome: "Colômbia", ddi: "+57" },
  { nome: "Equador", ddi: "+593" },
  { nome: "Venezuela", ddi: "+58" },
  { nome: "México", ddi: "+52" },
  { nome: "Panamá", ddi: "+507" },
  { nome: "Costa Rica", ddi: "+506" },
  { nome: "Cuba", ddi: "+53" },
  { nome: "República Dominicana", ddi: "+1809" },
  { nome: "Espanha", ddi: "+34" },
  { nome: "França", ddi: "+33" },
  { nome: "Itália", ddi: "+39" },
  { nome: "Alemanha", ddi: "+49" },
  { nome: "Reino Unido", ddi: "+44" },
  { nome: "Irlanda", ddi: "+353" },
  { nome: "Holanda", ddi: "+31" },
  { nome: "Bélgica", ddi: "+32" },
  { nome: "Suíça", ddi: "+41" },
  { nome: "Áustria", ddi: "+43" },
  { nome: "Suécia", ddi: "+46" },
  { nome: "Noruega", ddi: "+47" },
  { nome: "Dinamarca", ddi: "+45" },
  { nome: "Finlândia", ddi: "+358" },
  { nome: "Polônia", ddi: "+48" },
  { nome: "Grécia", ddi: "+30" },
  { nome: "Turquia", ddi: "+90" },
  { nome: "Rússia", ddi: "+7" },
  { nome: "Emirados Árabes Unidos", ddi: "+971" },
  { nome: "Arábia Saudita", ddi: "+966" },
  { nome: "Catar", ddi: "+974" },
  { nome: "Israel", ddi: "+972" },
  { nome: "Egito", ddi: "+20" },
  { nome: "África do Sul", ddi: "+27" },
  { nome: "Marrocos", ddi: "+212" },
  { nome: "Índia", ddi: "+91" },
  { nome: "China", ddi: "+86" },
  { nome: "Japão", ddi: "+81" },
  { nome: "Coreia do Sul", ddi: "+82" },
  { nome: "Tailândia", ddi: "+66" },
  { nome: "Vietnã", ddi: "+84" },
  { nome: "Indonésia", ddi: "+62" },
  { nome: "Filipinas", ddi: "+63" },
  { nome: "Malásia", ddi: "+60" },
  { nome: "Singapura", ddi: "+65" },
  { nome: "Austrália", ddi: "+61" },
  { nome: "Nova Zelândia", ddi: "+64" },
];
